### ISSUE TITLE
Setting up for private gitlab instance and VS debugging

### ISSUE THREAD

**Issue by lief480** [juangburgos/GitlabRewritter#1]
Can't figure out how to set this up with SourceLink debugging in Visual Studio. The example URL provided in the example doesn't seem to match the request being created by the debugger when calling into a private Gitlab server. Can you please provide additional details on how to set this up?

**Comment by juangburgos** [comment]
Hi, I don't know how familiar you are with Windows Debugging Tools, but you have to **index** your debug files (`*.pdb`) to point to the URL of your sources (in this case to match the URL exposed by your *GitlabRewritter* instance). You do this with the [PDBStr Tool](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/the-pdbstr-tool).

**Comment by lief480** [comment]
Ah so you are building your *.pdb files in a custom way. I am attempting to use the newer style [SourceLink](https://github.com/dotnet/sourcelink) setup, which auto configures the pdb generation based on your particular source provider (In my case a Private Gitlab instance). That uses a different URL format to reach the RAW endpoints in gitlab. That format is as follows: https://{gitlab_url}/{project_path}(seperated by slashes)/raw/{commit_hash}/{file_path}(separated by slashes)/{filename}. I will fork the project and see what I can come up with. Thanks for the help!

**Comment by juangburgos** [comment]
Not building them custom, but after buid, I index them. But yeah, you can also fork and adapt, the source code is super easy.
